### ISSUE TITLE
Maven repository

### ISSUE THREAD

**Issue by games647** [ST-DDT/CrazyLogin#4]
Do you have any plans on providing a maven repository for this project including CrazyCore?

**Comment by ST-DDT** [comment]
Yes, but currently there is an issue with CrazyCore setup. So I will just upload fake poms.

I'm not sure when/where i will be able to upload them though.

May I ask why you need this? Just curious.

**Comment by games647** [comment]
For FastLogin. I'm currently using system dependencies.

**Comment by games647** [comment]
Maybe at least an API version which is available in a maven repository and have the following methods:

isRegistered(UUID)
forceLogin(Player)
forceRegister(Player, String) - String -> password

**Comment by ST-DDT** [comment]
Active development has stopped.
