### ISSUE TITLE
Crash during data cleanup

### ISSUE THREAD

**Issue by GershonR** [ST-DDT/CrazyLogin#5]
http://pastebin.com/rLbChMhZ

**Comment by ST-DDT** [comment]
Thanks for the report. I look at it soon.
For the meantime you could temporarily disable the autoclean feature.

**Comment by GershonR** [comment]
Any news on this?

http://pastebin.com/wYX4pmLU

**Comment by GershonR** [comment]
Still need this so I can clean up my database, its getting to be pretty big and takes a long time to load on start up

**Comment by ST-DDT** [comment]
Sorry for the wait. I will try to fix it soon.

**Comment by ST-DDT** [comment]
@GershonR Please **test** this version: [CrazyLogin v7.23.5](https://dev.bukkit.org/projects/crazylogin/files/2396553)

**Comment by GershonR** [comment]
I have tried /crazylogin dropolddata 250 <mypassword> it caused the server to just lockup

https://pastebin.com/y3CpHFeD

**Comment by ST-DDT** [comment]
Thanks for the report i will attempt to fix it again.
My test accounts dont seem to be enough.

**Comment by GershonR** [comment]
I can provide my DB file if you need for testing

**Comment by ST-DDT** [comment]
I used a RNG to create some dummy entries.
[CrazyLogin v7.23.6](https://dev.bukkit.org/projects/crazylogin/files/2399735)
I hope this one works better.

Before deleting the data you have to set 
````yaml
broadcastPlayerDataRemoval: false
````
(PS the current/previous data cleanup is poorly implemented and properly fixing it would require a huge rewrite)

**Comment by GershonR** [comment]
Getting a broken link for v7.23.6 and I don't see the `broadcastPlayerDataRemoval: false` in my config.yml

**Comment by ST-DDT** [comment]
That file is currently under review. This may take a day. 
But you could also try the [one](https://github.com/ST-DDT/CrazyLogin/blob/master/CrazyLogin.jar?raw=true) from the repo.
The `broadcastPlayerDataRemoval` option has been added in that version.

**Comment by GershonR** [comment]
Still crashed unfortunately https://pastebin.com/xr5g0BCB

**Comment by ST-DDT** [comment]
Nice. Thanks for your report and tests.
