### ISSUE TITLE
Block Admin Login

### ISSUE THREAD

**Issue by GershonR** [ST-DDT/CrazyLogin#7]
Is it possible to check if a users IP is not on the whitelist of the account and kick them?

For example if any other user try to login as an admin it will kick them if their IP is not on the whitelist of that admin account

**Comment by ST-DDT** [comment]
There is no feature like this included in this plugin, but I guess you could use the [CrazyLoginFilter](https://dev.bukkit.org/projects/crazyloginfilter) plugin.

Any additional questions?

**Comment by GershonR** [comment]
Awesome I downloaded it and tried it out, but how do I create a filter on myself to allow only connections on my IP
