### ISSUE TITLE
Move after registration

### ISSUE THREAD

**Issue by GershonR** [ST-DDT/CrazyLogin#8]
I would like to a move a player after they have registered to a tutorial area, is it possible to add this to the config?

**Comment by GershonR** [comment]
Actually probably better would be having a list of commands to run after registration, so things like having the server warp them, give them items etc.

**Comment by ST-DDT** [comment]
Added in `v7.24.0` (Currently in review). Originally it was intended to use plugins for that that listen to the register event, but I guess the command list is much easier.

````yaml
afterRegistrationCommands:
- say Hello {name}
`````
* {name} will be replaced with the name of the player that registered.
* {uuid} will be replaced with the uuid of the player that registered.

Please test that version and give me feedback.

**Comment by GershonR** [comment]
Looks like it worked, I had to add that manually to the config since it was not added, but it send the hello, I will try to test with warps, and more commands soon

**Comment by GershonR** [comment]
Works perfectly, thanks alot!
